name: dart_countries
description: A set of informations about countries. Contains various maps and isoCodes.
version: 3.0.3
homepage: https://github.com/cedvdb/dart_countries

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  xml: ^5.1.2
  test: any
  basic_utils: ^3.1.0
