name: dart_countries
description: Dart countries. The countries' information contain Phone number meta data, languages, currencies, iso code...
version: 1.0.0
homepage: https://github.com/cedvdb/dart_countries

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  xml: ^5.1.2
  test: any
  basic_utils: ^3.1.0


